# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 汽车之家极速版

on:
  workflow_dispatch:
  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        QCZJ_GetUserInfoHEADER: ${{ secrets.QCZJ_GetUserInfoHEADER }}
        QCZJ_taskBODY: ${{ secrets.QCZJ_taskBODY }}		
        QCZJ_activityBODY: ${{ secrets.QCZJ_activityBODY }}	
        QCZJ_addCoinBODY: ${{ secrets.QCZJ_addCoinBODY }}
        QCZJ_addCoin2BODY: ${{ secrets.QCZJ_addCoin2BODY }}
        QCZJ_CASH: ${{ secrets.QCZJ_CASH }}
        QCZJ_CASHTIME: ${{ secrets.QCZJ_CASHTIME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: zyt821/QCZJ
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          npm install
      - name: '运行 【汽车之家极速版】'
        if: env.QCZJ_GetUserInfoHEADER
        run: |
          node Task/qczjspeed.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}

    
